/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type LegalPage = {
  _id: string;
  _type: "legalPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type FaqItem = {
  _id: string;
  _type: "faqItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question?: string;
  answer?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote?: string;
  name?: string;
  role?: string;
  company?: string;
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type WerkItem = {
  _id: string;
  _type: "werkItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  clientName?: string;
  summary?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  tags?: Array<string>;
  uitdaging?: string;
  oplossing?: string;
  results?: Array<string>;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  ctaLabel?: string;
  order?: number;
};

export type FaqItemReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "faqItem";
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading?: string;
  intro?: string;
  sessionHeading?: string;
  sessionBody?: string;
  faqHeading?: string;
  faqIntro?: string;
  faqs?: Array<
    {
      _key: string;
    } & FaqItemReference
  >;
  seo?: Seo;
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type WerkPage = {
  _id: string;
  _type: "werkPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading?: string;
  intro?: string;
  founderTeaser?: string;
  seo?: Seo;
};

export type JoinPage = {
  _id: string;
  _type: "joinPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading?: string;
  intro?: string;
  roleTitle?: string;
  roleCta?: Link;
  lookingForHeading?: string;
  lookingForIntro?: string;
  requirements?: Array<string>;
  whyHeading?: string;
  whyBody?: string;
  whyCta?: Link;
  seo?: Seo;
};

export type Link = {
  _type: "link";
  label?: string;
  url?: string;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading?: string;
  intro?: string;
  ambitieHeading?: string;
  ambitieBody?: string;
  beliefs?: Array<string>;
  weavrWordHeading?: string;
  weavrWordBody?: string;
  oorsprongHeading?: string;
  oorsprongBody?: string;
  brands?: Array<string>;
  caseStudies?: Array<
    {
      _key: string;
    } & CaseStudyBlock
  >;
  seo?: Seo;
};

export type ApproachPage = {
  _id: string;
  _type: "approachPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading?: string;
  intro?: string;
  stepsHeading?: string;
  stepsIntro?: string;
  steps?: Array<
    {
      _key: string;
    } & ApproachStep
  >;
  toolkitHeading?: string;
  toolkitIntro?: string;
  toolkitCategories?: Array<
    {
      _key: string;
    } & ToolkitCategory
  >;
  closingHeading?: string;
  closingCta?: Link;
  seo?: Seo;
};

export type TestimonialReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "testimonial";
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroHeading?: string;
  heroIntro?: string;
  heroCta?: Link;
  growthTeaserHeading?: string;
  growthTeaserCta?: Link;
  approachTeaserEyebrow?: string;
  approachTeaserHeading?: string;
  approachTeaserBody?: string;
  expertsTeaserEyebrow?: string;
  expertsTeaserHeading?: string;
  expertsTeaserBody?: string;
  testimonialsHeading?: string;
  testimonials?: Array<
    {
      _key: string;
    } & TestimonialReference
  >;
  ctaBannerHeading?: string;
  ctaBannerCta?: Link;
  seo?: Seo;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  phone?: string;
  email?: string;
  linkedinUrl?: string;
  footerNote?: string;
};

export type ToolkitCategory = {
  _type: "toolkitCategory";
  title?: string;
  description?: string;
  services?: Array<string>;
};

export type ApproachStepOption = {
  _type: "approachStepOption";
  title?: string;
  body?: string;
  cta?: Link;
};

export type ApproachStep = {
  _type: "approachStep";
  title?: string;
  body?: string;
  options?: Array<
    {
      _key: string;
    } & ApproachStepOption
  >;
  cta?: Link;
};

export type CaseStudyBlock = {
  _type: "caseStudyBlock";
  title?: string;
  uitdaging?: string;
  oplossing?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | LegalPage
  | Slug
  | FaqItem
  | SanityImageAssetReference
  | Testimonial
  | SanityImageCrop
  | SanityImageHotspot
  | WerkItem
  | FaqItemReference
  | ContactPage
  | Seo
  | WerkPage
  | JoinPage
  | Link
  | AboutPage
  | ApproachPage
  | TestimonialReference
  | HomePage
  | SiteSettings
  | ToolkitCategory
  | ApproachStepOption
  | ApproachStep
  | CaseStudyBlock
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0]
export type SITE_SETTINGS_QUERY_RESULT = {
  _id: "siteSettings";
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  phone?: string;
  email?: string;
  linkedinUrl?: string;
  footerNote?: string;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_type == "homePage" && _id == "homePage"][0]{    ...,    testimonials[]->{_id, quote, name, role, company, avatar}  }
export type HOME_PAGE_QUERY_RESULT = {
  _id: "homePage";
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroHeading?: string;
  heroIntro?: string;
  heroCta?: Link;
  growthTeaserHeading?: string;
  growthTeaserCta?: Link;
  approachTeaserEyebrow?: string;
  approachTeaserHeading?: string;
  approachTeaserBody?: string;
  expertsTeaserEyebrow?: string;
  expertsTeaserHeading?: string;
  expertsTeaserBody?: string;
  testimonialsHeading?: string;
  testimonials: Array<{
    _id: string;
    quote: string | null;
    name: string | null;
    role: string | null;
    company: string | null;
    avatar: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  }> | null;
  ctaBannerHeading?: string;
  ctaBannerCta?: Link;
  seo?: Seo;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: APPROACH_PAGE_QUERY
// Query: *[_type == "approachPage" && _id == "approachPage"][0]
export type APPROACH_PAGE_QUERY_RESULT = {
  _id: "approachPage";
  _type: "approachPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading?: string;
  intro?: string;
  stepsHeading?: string;
  stepsIntro?: string;
  steps?: Array<
    {
      _key: string;
    } & ApproachStep
  >;
  toolkitHeading?: string;
  toolkitIntro?: string;
  toolkitCategories?: Array<
    {
      _key: string;
    } & ToolkitCategory
  >;
  closingHeading?: string;
  closingCta?: Link;
  seo?: Seo;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: ABOUT_PAGE_QUERY
// Query: *[_type == "aboutPage" && _id == "aboutPage"][0]
export type ABOUT_PAGE_QUERY_RESULT = {
  _id: "aboutPage";
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading?: string;
  intro?: string;
  ambitieHeading?: string;
  ambitieBody?: string;
  beliefs?: Array<string>;
  weavrWordHeading?: string;
  weavrWordBody?: string;
  oorsprongHeading?: string;
  oorsprongBody?: string;
  brands?: Array<string>;
  caseStudies?: Array<
    {
      _key: string;
    } & CaseStudyBlock
  >;
  seo?: Seo;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: JOIN_PAGE_QUERY
// Query: *[_type == "joinPage" && _id == "joinPage"][0]
export type JOIN_PAGE_QUERY_RESULT = {
  _id: "joinPage";
  _type: "joinPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading?: string;
  intro?: string;
  roleTitle?: string;
  roleCta?: Link;
  lookingForHeading?: string;
  lookingForIntro?: string;
  requirements?: Array<string>;
  whyHeading?: string;
  whyBody?: string;
  whyCta?: Link;
  seo?: Seo;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: WERK_PAGE_QUERY
// Query: *[_type == "werkPage" && _id == "werkPage"][0]
export type WERK_PAGE_QUERY_RESULT = {
  _id: "werkPage";
  _type: "werkPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading?: string;
  intro?: string;
  founderTeaser?: string;
  seo?: Seo;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: WERK_ITEMS_QUERY
// Query: *[_type == "werkItem"] | order(order asc){    _id, title, slug, clientName, summary, coverImage, gallery, tags, ctaLabel  }
export type WERK_ITEMS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  clientName: string | null;
  summary: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  gallery: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
  tags: Array<string> | null;
  ctaLabel: string | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: WERK_ITEM_QUERY
// Query: *[_type == "werkItem" && slug.current == $slug][0]
export type WERK_ITEM_QUERY_RESULT = {
  _id: string;
  _type: "werkItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  clientName?: string;
  summary?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  tags?: Array<string>;
  uitdaging?: string;
  oplossing?: string;
  results?: Array<string>;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  ctaLabel?: string;
  order?: number;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: CONTACT_PAGE_QUERY
// Query: *[_type == "contactPage" && _id == "contactPage"][0]{    ...,    faqs[]->{_id, question, answer}  }
export type CONTACT_PAGE_QUERY_RESULT = {
  _id: "contactPage";
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading?: string;
  intro?: string;
  sessionHeading?: string;
  sessionBody?: string;
  faqHeading?: string;
  faqIntro?: string;
  faqs: Array<{
    _id: string;
    question: string | null;
    answer: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
  }> | null;
  seo?: Seo;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: LEGAL_PAGE_QUERY
// Query: *[_type == "legalPage" && slug.current == $slug][0]
export type LEGAL_PAGE_QUERY_RESULT = {
  _id: string;
  _type: "legalPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "siteSettings" && _id == "siteSettings"][0]': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_type == "homePage" && _id == "homePage"][0]{\n    ...,\n    testimonials[]->{_id, quote, name, role, company, avatar}\n  }\n': HOME_PAGE_QUERY_RESULT;
    '*[_type == "approachPage" && _id == "approachPage"][0]': APPROACH_PAGE_QUERY_RESULT;
    '*[_type == "aboutPage" && _id == "aboutPage"][0]': ABOUT_PAGE_QUERY_RESULT;
    '*[_type == "joinPage" && _id == "joinPage"][0]': JOIN_PAGE_QUERY_RESULT;
    '*[_type == "werkPage" && _id == "werkPage"][0]': WERK_PAGE_QUERY_RESULT;
    '\n  *[_type == "werkItem"] | order(order asc){\n    _id, title, slug, clientName, summary, coverImage, gallery, tags, ctaLabel\n  }\n': WERK_ITEMS_QUERY_RESULT;
    '\n  *[_type == "werkItem" && slug.current == $slug][0]\n': WERK_ITEM_QUERY_RESULT;
    '\n  *[_type == "contactPage" && _id == "contactPage"][0]{\n    ...,\n    faqs[]->{_id, question, answer}\n  }\n': CONTACT_PAGE_QUERY_RESULT;
    '\n  *[_type == "legalPage" && slug.current == $slug][0]\n': LEGAL_PAGE_QUERY_RESULT;
  }
}
